#b站视频解析开关,false时不解析
isjx: true
#b站cookie
cookie: ""
#qn80（1080p）,64(720p),32(480p),16(360p),112(1080p+),116(1080p60),120(4k)
qn: 120
#视频信息卡片，false时不显示
card: true
#b站动态推送时间间隔（最小为1,最大为60）单位分钟
dynamicTime: 5
#b站直播推送时间间隔（最小为1,最大为60）单位分钟
liveTime: 5
