#帮助列表
randomImgOpen: true
helplist:
  - title: 视频解析功能
    list:
      - title: b站解析
        desc: 检测到卡片自动解析视频，1080p及以上画质需要b站ck
        icon: "142"
      - title: "抖音解析"
        desc: 检测到抖音分享链接自动解析视频
        icon: "142"
      - title: "qq小世界解析"
        desc: 检测到小世界分享卡片自动解析视频
        icon: "142"
      - title: "快手解析"
        desc: 检测到快手分享链接自动解析视频
        icon: "142"

  - title: b站功能
    list:
      - title: "#订阅(直播|文字|图文|视频|转发|专栏)up+uid"
        desc: 订阅up主的动态以及直播动态，有指定类型时仅推送当前类别的动态，默认为全部推送,在动态更新时推送
        icon: "#取消订阅up+uid"
      - title: "#取消订阅(直播|文字|图文|视频|转发|专栏)up+uid"
        desc: 取消订阅up主的动态，不指定类型为全部动态
        icon: "142"
      - title: "#订阅列表"
        desc: 查看当前群所有订阅的up主
        icon: "142"
      - title: "#查询up最新动态+uid"
        desc: 查看up主的最新动态
        icon: "142"
      - title: "#(取消)直播推送全体+uid"
        desc: 直播推送是否@全体成员
        icon: "142"

  - title: 群功能
    list:
      - title: "#水群统计"
        desc: 让我看看群里的大水比是谁
        icon: "141"
      - title: "#今日发言记录"
        desc: 查看自己今天的发言记录可以@群友查看群友的发言记录
        icon: "143"
      - title: 引用撤回
        desc: 在机器人发送的消息回复撤回，机器人会撤回该消息
        icon: "141"
      - title: "#伪装@群友"
        desc: 机器人换上at用户的头像昵称，并在10分钟内复读at用户的发言
        icon: "141"
      - title: "#停止|结束伪装"
        desc: 停止机器人的伪装
        icon: "141"
      - title: "早安/晚安"
        desc: 记录早晚安时间
        icon: "141"
      - title: "睡眠信息"
        desc: 从早晚安记录的时间分析睡眠信息
        icon: "141"
      - title: "你主人是谁"
        desc: 给机器人找找迷路的主人
        icon: "141"

  - title: 其他功能
    list:
      - title: "千羽ai功能"
        desc: 通过#千羽设置查看具体功能
        icon: "141"
      - title: "群聊表情包学习功能"
        desc: 每天从昨天的聊天记录中学习表情包
        icon: "141"
      - title: "达咩/哒咩"
        desc: 删除机器人所学习不对的表情包
        icon: "141"
      - title: "#查看所有表情"
        desc: 查看机器人当前群聊所学习的表情包，后面跟数字为第几页
        icon: "141"
      - title: "#清理过期表情包"
        desc: 清理这个群的过期表情包
        icon: "141"
      - title: "千羽戳一戳"
        desc: 戳一戳发送当前群聊所学习的表情包
        icon: "141"
      - title: "api帮助"
        desc: 查看具体api的帮助
        icon: "141"
      - title: "网页截图"
        desc: 发送网址后机器人会自动发送网页截图
        icon: "141"
  - title: 管理员功能
    list:
      - title: "#千羽帮助"
        desc: 勉强能看就行
        icon: "100"
      - title: "#千羽（强制）更新"
        desc: 更新千羽（重置版）
        icon: "100"
      - title: "#千羽更新日志"
        desc: 获取本地更新日志
        icon: "100"
      - title: "#千羽设置"
        desc: 打开设置面板
        icon: "100"
      - title: "#设置前缀+名称"
        desc: 设置当前群聊的机器人前缀
        icon: "100"
      - title: "#群前缀开启/关闭"
        desc: 开启/关闭群前缀
        icon: "100"
      - title: "#设置尾缀+名称"
        desc: 设置当前群聊的机器人发送消息的尾缀
        icon: "100"
      - title: "#尾缀开启/关闭"
        desc: 开启/关闭尾缀
        icon: "100"
      - title: "#设置b站ck"
        desc: 设置机器人的b站cookie
        icon: "100"
      - title: "#清除伪装缓存"
        desc: 清除本地缓存的伪装数据，防止恢复时信息错误
        icon: "100"
      - title: "#群聊复读开启/关闭"
        desc: 开启关闭群聊复读功能（被动复读）
        icon: "100"
      - title: "#打断复读开启/关闭"
        desc: 开启关闭打断群聊复读功能
        icon: "100"
      - title: "#设置伪装cd10"
        desc: 设置伪装cd为10分钟
        icon: "100"
      - title: "#设置伪装时长10"
        desc: 设置伪装的时长为10分钟
        icon: "100"
      - title: "#设置伪装次数上限10"
        desc: 设置每天伪装的次数上限为10
        icon: "100"
      - title: "#设置伪装群友次数1"
        desc: 设置每天伪装群友的伪装次数上限为1
        icon: "100"
      - title: "api检测"
        desc: 检测api是否能正常使用
        icon: "100"
      - title: "#千羽开机|关机"
        desc: 关闭千羽插件的所有功能
        icon: "100"
      - title: "#千羽群功能开启|关闭"
        desc: 关闭千羽插件在当前群的所有功能
        icon: "100"
      - title: "#千羽管理"
        desc: 管理千羽插件功能禁用和开启
        icon: "100"
